name: Context

on: [push]

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: dumnp
        run: |
          echo ${{ contains('hello','ll')}}
          echo ${{ startsWith('hello','he') }}
          echo ${{ endsWith('hello','lo') }}
          echo ${{ format('Hello {0} {1} {2}','World','!', '!') }}
  contextJob:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job Context
        env:
          JOB:CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps Context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner Context
        env: 
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: | 
          echo "$RUNNER_CONTEXT"
          echo "--------------------------------------------------"




