name: Container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: log node version
        run: node -v

      - name: Step with docker
        uses: docker://node:12.14.1-alpine3.10
        with: 
          entrypoint: '/bin/echo'
          args: 'Hello World...!!'

      - name: Log node version inside docker container
        uses: docker://node:12.14.1-alpine3.10
        with: 
          entrypoint: /usr/local/bin/node
          args: -v

      - uses: actions/checkout@v1

      - name: Run Script inside docker container
        uses: docker://node:12.14.1-alpine3.10
        with: 
          entrypoint: ./script.sh
          args: "Some Sring as argument"

      - name: Generte random variable value
        run: |
          RANDOM=`date | base64`
          echo "RANDOM=$RANDOM"
          echo "RANDOM=$RANDOM" >> $GITHUB_ENV

      - name: Send Slack Message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Hello Salck: ${{ env.RANDOM }}"

  node-docker:
    runs-on: ubuntu-latest
    services: 
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-type: application/json' -d '{\"username\":\"hello\", \"address\":\"dwded\"}'"
      - name: Get users
        run: curl http://localhost:3001/api/users
          