name: Context

on: [push, pull_request]

jobs:
  functions:
    runs-on: ubuntu-latest
    #timeout-minutes: 360
    steps:
      - name: dumnp
        run: |
          echo ${{ contains('hello','ll')}}
          echo ${{ startsWith('hello','he') }}
          echo ${{ endsWith('hello','lo') }}
          echo ${{ format('Hello {0} {1} {2}','World','!', '!') }}

  contextJob:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: eccho "$GITHUB_CONTEXT"
        #continue-on-error: true
      - name: Dump job Context
        if: failure()
        env:
          JOB:CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps Context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner Context
        if: always()
        env: 
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: | 
          echo "$RUNNER_CONTEXT"
          echo "--------------------------------------------------"




